name: Build plugin

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cs'
      - '**.csproj'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run build
        run: dotnet build
      - name: Create output directory
        run: |
          mkdir -p output/CS2AnnouncementBroadcaster
          mv ./bin/Debug/net8.0/CS2AnnouncementBroadcaster.dll output/CS2AnnouncementBroadcaster/
          mv ./bin/Debug/net8.0/CS2AnnouncementBroadcaster.pdb output/CS2AnnouncementBroadcaster/
          mv ./bin/Debug/net8.0/CS2AnnouncementBroadcaster.deps.json output/CS2AnnouncementBroadcaster/
          mv ./cfg output/CS2AnnouncementBroadcaster/
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: CS2AnnouncementBroadcaster-${{ github.sha }}
          path: output
  
  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: CS2AnnouncementBroadcaster-${{ github.sha }}
      - name: Create release assets
        run: |
          zip -r CS2AnnouncementBroadcaster-${{ github.sha }}.zip ./CS2AnnouncementBroadcaster
      - name: Get release info
        run: |
          RELEASE_INFO=$(curl -sH 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/${{ github.repository }}/releases)
          export UPLOAD_URL=$(echo $RELEASE_INFO | jq -r ".[] | select(.tag_name == \"${{ github.event.release.tag_name }}\").upload_url")
          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./CS2AnnouncementBroadcaster-${{ github.sha }}.zip
          asset_name: "CS2AnnouncementBroadcaster-${{ github.event.release.tag_name }}.zip"
          asset_content_type: application/zip

      # - name: Upload release asset
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: openprefireprac-${{ github.event.release.tag_name }}.zip
      #     files: 
      #       ./OpenPrefirePrac-${{ github.sha }}.zip

      # - name: Upload release asset
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: